server:
  port: 8080

eureka:   #<1>
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    statusPageUrlPath: /actuator/info      #状态地址
    healthCheckUrlPath: /actuator/health   #健康检查地址
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign      