info:
  scm-url: "@scm.url@"
  build-url: "https://github.com/shenxinli/spring-cloud-stage"
  
server:
  port: 8787

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    statusPageUrlPath: /actuator/info      #状态地址
    healthCheckUrlPath: /actuator/health   #健康检查地址
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

---
spring:
  cloud:
    config:
      enabled: true
      name: boorstrip,application,demo
      label: dev
      server:
        git:
          uri: https://github.com/shenxinli/config-repo
          search-paths: "{profile}"
          username: shenxinli
          password: chinaway2014
          basedir: /data
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
