server:
  port: 8787

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${security.user.name}:${security.user.password}@${spring.cloud.eureka.server.host.name}:${spring.cloud.eureka.server.host.port}/eureka/

spring:
  cloud:
    config:
      enabled: true
      name: bootstrap,application
      label: master
      server:
        git:
          uri: https://github.com/shenxinli/config-repo
          search-paths: ${profile}
          username: ${security.git.username}
          password: ${security.git.password}
          basedir: /data
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: "target/config-server.log"